### ISSUE TITLE
BlackSOD launch report

### ISSUE THREAD

**Issue by Coffeegrounds** [GuerrillaWar/WaveCOM#6]
Thanks for taking a look.

[Launch.txt](https://github.com/GuerrillaWar/WaveCOM/files/358359/Launch.txt)

**Comment by bountygiver** [comment]
Black screen should be fixed now that we have removed UIScreenListener that reference to bunch of objects which is known to cause this issue

**Comment by Coffeegrounds** [comment]
Same problem. Did a fresh install again and nothing changed. I get the operation gatecrasher cinematic sound with a black screen, click to skip, and hear it loading while still black screened.

I don't have any other mods turned on but I could unsub from them all if you think it'd help.

[BlackSODLaunch11-21-16.txt](https://github.com/GuerrillaWar/WaveCOM/files/603243/BlackSODLaunch11-21-16.txt)

**Comment by bountygiver** [comment]
if you get the cinematic in black screen then something is wrong with your game, you need to do a verify game cache.

**Comment by Coffeegrounds** [comment]
1 file was re-downloaded but the problem persisted. Also updated my graphics drivers.

[BlackSODLaunch11-25-16.txt](https://github.com/GuerrillaWar/WaveCOM/files/613945/BlackSODLaunch11-25-16.txt)
